objects/Audit_Score_Card__c.object
<CustomObject>
    <description>Audit Score Cards</description>
    <fields>
        <fullName>Product_Group_10__c</fullName>
        <description>Product Group 10</description>
        <inlineHelpText>Product Group 10</inlineHelpText>
        <label>Product Group 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_1__c</fullName>
        <description>Product Group 1</description>
        <inlineHelpText>Product Group 1</inlineHelpText>
        <label>Product Group 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_2__c</fullName>
        <description>Product Group 2</description>
        <inlineHelpText>Product Group 2</inlineHelpText>
        <label>Product Group 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_3__c</fullName>
        <description>Product Group 3</description>
        <inlineHelpText>Product Group 3</inlineHelpText>
        <label>Product Group 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_4__c</fullName>
        <description>Product Group 4</description>
        <inlineHelpText>Product Group 4</inlineHelpText>
        <label>Product Group 4</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_5__c</fullName>
        <description>Product Group 5</description>
        <inlineHelpText>Product Group 5</inlineHelpText>
        <label>Product Group 5</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_6__c</fullName>
        <description>Product Group 6</description>
        <inlineHelpText>Product Group 6</inlineHelpText>
        <label>Product Group 6</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_7__c</fullName>
        <description>Product Group 7</description>
        <inlineHelpText>Product Group 7</inlineHelpText>
        <label>Product Group 7</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_8__c</fullName>
        <description>Product Group 8</description>
        <inlineHelpText>Product Group 8</inlineHelpText>
        <label>Product Group 8</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_9__c</fullName>
        <description>Product Group 9</description>
        <inlineHelpText>Product Group 9</inlineHelpText>
        <label>Product Group 9</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Audit Score Card</label>
    <nameField>
        <label>Audit Score Cared</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Score Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <description>Country</description>
    <fields>
        <fullName>FS_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS Country</description>
        <inlineHelpText>FS Country</inlineHelpText>
        <label>FS Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Group_10__c</fullName>
        <description>Product Group 10</description>
        <inlineHelpText>Product Group 10</inlineHelpText>
        <label>Product Group 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_1__c</fullName>
        <description>Product Group 1</description>
        <inlineHelpText>Product Group 1</inlineHelpText>
        <label>Product Group 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_2__c</fullName>
        <description>Product Group 2</description>
        <inlineHelpText>Product Group 2</inlineHelpText>
        <label>Product Group 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_3__c</fullName>
        <description>Product Group 3</description>
        <inlineHelpText>Product Group 3</inlineHelpText>
        <label>Product Group 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_4__c</fullName>
        <description>Product Group 4</description>
        <inlineHelpText>Product Group 4</inlineHelpText>
        <label>Product Group 4</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_5__c</fullName>
        <description>Product Group 5</description>
        <inlineHelpText>Product Group 5</inlineHelpText>
        <label>Product Group 5</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_6__c</fullName>
        <description>Product Group 6</description>
        <inlineHelpText>Product Group 6</inlineHelpText>
        <label>Product Group 6</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_7__c</fullName>
        <description>Product Group 7</description>
        <inlineHelpText>Product Group 7</inlineHelpText>
        <label>Product Group 7</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_8__c</fullName>
        <description>Product Group 8</description>
        <inlineHelpText>Product Group 8</inlineHelpText>
        <label>Product Group 8</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_9__c</fullName>
        <description>Product Group 9</description>
        <inlineHelpText>Product Group 9</inlineHelpText>
        <label>Product Group 9</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CountryScoreCard__c.object
<CustomObject>
    <description>Country Score Card</description>
    <fields>
        <fullName>Audit_Score_Card__c</fullName>
        <label>Audit Score Card</label>
        <referenceTo>Audit_Score_Card__c</referenceTo>
        <relationshipLabel>CountryScoreCards</relationshipLabel>
        <relationshipName>CountryScoreCards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>CountryScoreCards</relationshipLabel>
        <relationshipName>CountryScoreCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Group_10__c</fullName>
        <description>Product Group 10</description>
        <inlineHelpText>Product Group 10</inlineHelpText>
        <label>Product Group 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_1__c</fullName>
        <description>Product Group 1</description>
        <inlineHelpText>Product Group 1</inlineHelpText>
        <label>Product Group 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_2__c</fullName>
        <description>Product Group 2</description>
        <inlineHelpText>Product Group 2</inlineHelpText>
        <label>Product Group 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_3__c</fullName>
        <description>Product Group 3</description>
        <inlineHelpText>Product Group 3</inlineHelpText>
        <label>Product Group 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_4__c</fullName>
        <description>Product Group 4</description>
        <inlineHelpText>Product Group 4</inlineHelpText>
        <label>Product Group 4</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_5__c</fullName>
        <description>Product Group 5</description>
        <inlineHelpText>Product Group 5</inlineHelpText>
        <label>Product Group 5</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_6__c</fullName>
        <description>Product Group 6</description>
        <inlineHelpText>Product Group 6</inlineHelpText>
        <label>Product Group 6</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_7__c</fullName>
        <description>Product Group 7</description>
        <inlineHelpText>Product Group 7</inlineHelpText>
        <label>Product Group 7</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_8__c</fullName>
        <description>Product Group 8</description>
        <inlineHelpText>Product Group 8</inlineHelpText>
        <label>Product Group 8</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_9__c</fullName>
        <description>Product Group 9</description>
        <inlineHelpText>Product Group 9</inlineHelpText>
        <label>Product Group 9</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CountryScoreCard</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>CountryScoreCard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CountryScoreCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product_Group__c.object
<CustomObject>
    <description>Product Group Definition</description>
    <fields>
        <fullName>PrdGrpAssociation__c</fullName>
        <description>Product Group Association</description>
        <inlineHelpText>Product Group Association</inlineHelpText>
        <label>PrdGrpAssociation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Group</label>
    <nameField>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CountryScoreCardCreation.cls
global class CountryScoreCardCreation {

    
    webservice static String crtCntryScoreCard() {
 
    integer k = 0;
    integer i = 0;   
    integer j = 0;  
        
  // Read all product groups    
 	List<Product_Group__c> nproductGroup = [Select i.Name, i.PrdGrpAssociation__c
                                                  From Product_Group__c i]; 
        
  // Read all countries        
       List<Country__c> ncountry = [Select i.id, i.Name 
                                                  From Country__c i 
                                           Where i.FS_Country__c = True];
        
   // Read all score cards     
   		 List<Audit_Score_Card__c> nscorecard = [Select i.id, i.Name 
                                                  From Audit_Score_Card__c i ];
                                      


 //Create country score card record with output table
 //     

       List<CountryScoreCard__c> scorecardlist = new List<CountryScoreCard__c>();

// Loop over FS Countries
        for(Country__c cntry : ncountry){
             
           
            
 
            
            k = 0;
 // Loop over Audit Score Cards           
             for(Audit_Score_Card__c  scorecard : nscorecard){
                CountryScoreCard__c ncntryscorecard = new CountrySCoreCard__c();
                ncntryscorecard.Country__c = ncountry[i].id;
                ncntryscorecard.Audit_Score_Card__c = nscorecard[k].id;
                system.debug('Audit Score Card ID ' +ncntryscorecard.Audit_Score_Card__c);
                   j = 0;
    				    for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 1){
                  			   ncntryscorecard.Product_Group_1__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }
                 
       				j = 0; 
      				    for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 2){
                  			   ncntryscorecard.Product_Group_2__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }
        
       			 j = 0; 
        			   for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 3){
                  			   ncntryscorecard.Product_Group_3__c = nproductGroup[j].name;                   
		              	       break;
               				  }
               			  j++;
            			 }
       
      		    j = 0; 
       			   for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 4){
                  			   ncntryscorecard.Product_Group_4__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }     
       		  j = 0; 
          	  for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 5){
                  			   ncntryscorecard.Product_Group_5__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 } 
       
             j = 0; 
       		   for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 6){
                  			   ncntryscorecard.Product_Group_6__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }      
         			    j = 0; 
      		 		  for(Product_Group__c prdgrp : nproductGroup){ 			
               				  if(nproductGroup[j].PrdGrpAssociation__c == 7){
                  			   ncntryscorecard.Product_Group_7__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }
         		    j = 0; 
           			  for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 8){
                  			   ncntryscorecard.Product_Group_8__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }     
          			 j = 0; 
      				  for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 9){
                  			   ncntryscorecard.Product_Group_9__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }   
     			 	 j = 0; 
      				  for(Product_Group__c prdgrp : nproductGroup){ 
               				  if(nproductGroup[j].PrdGrpAssociation__c == 10){
                  			   ncntryscorecard.Product_Group_10__c = nproductGroup[j].name;                   
		              	       break;
               			  }
               			  j++;
            			 }     
         // Add country score card record to output table  

            system.debug('Country id  ' + ncntryscorecard.Country__c);
       //     system.debug('Audit Score Card ' + ncntryscorecard.Audit_Score_Card__c);
            system.debug('Product Group 1 ' + ncntryscorecard.Product_Group_1__c);
       		  scorecardlist.add(ncntryscorecard);
                 
            
              k++;

             }  
            i++;

        }

        
        system.debug('Number of elements ' + scorecardlist.size());
        
  // Output CountryScoreCards      
            try {
            Database.upsert(scorecardlist);
              }
            catch(DmlException e) {
                return e.getMessage();
          }
        
      return 'Country Score Card Created';
        
    }
  
    

    
}