objects/CountryScoreCard__c.object
<CustomObject>
    <description>Country Score Card</description>
    <fields>
        <fullName>PrdGrp10__c</fullName>
        <description>Product Group 10 Count</description>
        <inlineHelpText>Product Group 10 Count</inlineHelpText>
        <label>PrdGrp10</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp1__c</fullName>
        <description>Product Group 1 Count</description>
        <inlineHelpText>Product Group 1 Count</inlineHelpText>
        <label>PrdGrp1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp2__c</fullName>
        <description>Product Group 2 Count</description>
        <inlineHelpText>Product Group 2 Count</inlineHelpText>
        <label>PrdGrp2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp3__c</fullName>
        <description>Product Group 3 Count</description>
        <inlineHelpText>Product Group 3 Count</inlineHelpText>
        <label>PrdGrp3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp4__c</fullName>
        <description>Product Group 4 Count</description>
        <inlineHelpText>Product Group 4 Count</inlineHelpText>
        <label>PrdGrp4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp5__c</fullName>
        <description>Product Group 5 Count</description>
        <inlineHelpText>Product Group 5 Count</inlineHelpText>
        <label>PrdGrp5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp6__c</fullName>
        <description>Product Group 6 Count</description>
        <inlineHelpText>Product Group 6 Count</inlineHelpText>
        <label>PrdGrp6</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp7__c</fullName>
        <description>Product Group 7 Count</description>
        <inlineHelpText>Product Group 7 Count</inlineHelpText>
        <label>PrdGrp7</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp8__c</fullName>
        <description>Product Group 8 Count</description>
        <inlineHelpText>Product Group 8 Count</inlineHelpText>
        <label>PrdGrp8</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrdGrp9__c</fullName>
        <description>Product Group 9 Count</description>
        <inlineHelpText>Product Group 9 Count</inlineHelpText>
        <label>PrdGrp9</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Group_10__c</fullName>
        <description>Product Group 10</description>
        <inlineHelpText>Product Group 10</inlineHelpText>
        <label>Product Group 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_1__c</fullName>
        <description>Product Group 1</description>
        <inlineHelpText>Product Group 1</inlineHelpText>
        <label>Product Group 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_2__c</fullName>
        <description>Product Group 2</description>
        <inlineHelpText>Product Group 2</inlineHelpText>
        <label>Product Group 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_3__c</fullName>
        <description>Product Group 3</description>
        <inlineHelpText>Product Group 3</inlineHelpText>
        <label>Product Group 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_4__c</fullName>
        <description>Product Group 4</description>
        <inlineHelpText>Product Group 4</inlineHelpText>
        <label>Product Group 4</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_5__c</fullName>
        <description>Product Group 5</description>
        <inlineHelpText>Product Group 5</inlineHelpText>
        <label>Product Group 5</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_6__c</fullName>
        <description>Product Group 6</description>
        <inlineHelpText>Product Group 6</inlineHelpText>
        <label>Product Group 6</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_7__c</fullName>
        <description>Product Group 7</description>
        <inlineHelpText>Product Group 7</inlineHelpText>
        <label>Product Group 7</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_8__c</fullName>
        <description>Product Group 8</description>
        <inlineHelpText>Product Group 8</inlineHelpText>
        <label>Product Group 8</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_9__c</fullName>
        <description>Product Group 9</description>
        <inlineHelpText>Product Group 9</inlineHelpText>
        <label>Product Group 9</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CountryScoreCard</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>CountryScoreCard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CountryScoreCards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <description>Production Facility</description>
    <fields>
        <fullName>Engineering_Audit_Requested__c</fullName>
        <description>Engineering Audit Requested</description>
        <inlineHelpText>Engineering Audit Requested</inlineHelpText>
        <label>Engineering Audit Requested</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Engineering_audit_completed__c</fullName>
        <formula>AND(ISPICKVAL(Engineering_Audit_Requested__c  , &quot;Yes&quot;),

AND(NOT(ISBLANK(TEXT( Electrical_Safety_Audit__c ))),
NOT(ISBLANK(TEXT(  Structural_Audit__c  ))),
NOT(ISBLANK(TEXT(   Other_Audits__c   ))),
NOT(ISBLANK(TEXT(   Fire_Safety_Audit__c   )))),

ISPICKVAL(  Facility_Status__c  ,&quot;Active&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Engineering audit completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Audit_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS Audit Required</description>
        <inlineHelpText>FS Audit Required</inlineHelpText>
        <label>FS Audit Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_CAPA_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS CAPA Completed</description>
        <inlineHelpText>Audit Group  = FS FOLLOW UP and
Factory Status  = ACTIVE  and
Audit Date = NOT BLANK and
FS Audit Required = NOT BLANK</inlineHelpText>
        <label>FS CAPA Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_CAPA_Not_Requested__c</fullName>
        <formula>AND(   Pending_CAPA_FS__c   = FALSE ,
   Past_CAPA_Deadline_FS__c    = FALSE,
              FS_CAPA_Completed__c    = FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FS CAPA Not Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS Compliant</description>
        <inlineHelpText>Audit Group = PERIODIC FS and
Factory Status = ACTIVE and
FS Audit Required = NOT BLANK and
Audit Date  &gt;= TODAY()-365*3</inlineHelpText>
        <label>FS Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Facility_Number__c</fullName>
        <description>Facility Number</description>
        <displayFormat>{0000000}</displayFormat>
        <inlineHelpText>Facility Number</inlineHelpText>
        <label>Facility Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Past_Audit_Deadline_FS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Past Audit Deadline (FS)</description>
        <inlineHelpText>Audit Group = PERIODIC FS and
Factory Status  = ACTIVE and
Audit Date = NOT BLANK and
Audit Date &lt; TODAY()-365*3 and
FS Audit Required = NOT BLANK</inlineHelpText>
        <label>Past Audit Deadline (FS)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_Audit_Deadline_WCA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Past Audit Deadline (WCA)</description>
        <inlineHelpText>Audit Group = ANNUAL WCA and
Factory Status  = ACTIVE and
Audit Date &lt; TODAY()-365 and
Audit date = NOT BLANK</inlineHelpText>
        <label>Past Audit Deadline (WCA)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_CAPA_Deadline_FS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Past CAPA Deadline (FS)</description>
        <inlineHelpText>Past CAPA Deadline (FS)
Audit Group  = FS FOLLOW UP and
Factory Status = ACTIVE and
Audit Date = BLANK and
CAPA Due Date  &lt; TODAY() (DUE DATE a result of selecting 1/3/6 months) and
FS Audit Required  = NOT BLANK</inlineHelpText>
        <label>Past CAPA Deadline (FS)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Past_CAPA_Deadline_WCA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Past CAPA Deadline (WCA)</description>
        <inlineHelpText>Past CAPA Deadline (WCA)
Audit Group  = WCA FOLLOW UP and
Factory Status = ACTIVE and
Audit Date = BLANK and
CAPA Due Date  &lt; TODAY() (DUE DATE a result of selecting 1/3/6 months) and</inlineHelpText>
        <label>Past CAPA Deadline (WCA)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pending_CAPA_FS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pending CAPA (FS)</description>
        <inlineHelpText>Audit Group = FS FOLLOW UP and
FACTORY STATUS = ACTIVE and
Audit Date = BLANK and
CAPA Due Date &gt;= TODAY() and
FS Audi Required = NOT BLANK</inlineHelpText>
        <label>Pending CAPA (FS)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pending_CAPA_WCA__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Pending CAPA (WCA)</description>
        <inlineHelpText>Audit Group = WCA FOLLOW UP and
Factory Status  = ACTIVE and
Audit Date = BLANK and
CAPA Due Date &gt;= TODAY()</inlineHelpText>
        <label>Pending CAPA (WCA)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Training Completed</description>
        <inlineHelpText>Training Completed</inlineHelpText>
        <label>Training Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_Not_Completed__c</fullName>
        <description>Training Not Completed</description>
        <formula>AND(OR(ISPICKVAL(Facility_Status__c, &quot;Active&quot;)),
 ISPICKVAL( FS_Training_request__c , &quot;Yes&quot;),
 ISBLANK(FS_Training_date__c )
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Facility Status = Active and
FS Training Request = Yes and
FS Training Date = Blank</inlineHelpText>
        <label>Training Not Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Training_not_requested__c</fullName>
        <description>Training not requested</description>
        <formula>AND(OR(ISPICKVAL(Facility_Status__c, &quot;Active&quot;),ISPICKVAL(Facility_Status__c, &quot;Manual Accept Shipments&quot;)),
OR(
 ISPICKVAL( FS_Training_request__c , &quot;No&quot;),
 ISBLANK(TEXT(FS_Training_request__c)))

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Facility Status = Active or Manual Accept Shipments and
FS Training Request = No or Blank</inlineHelpText>
        <label>Training not requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WCA_CAPA_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WCA CAPA Completed</description>
        <inlineHelpText>WCA CAPA Completed</inlineHelpText>
        <label>WCA CAPA Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WCA_CAPA_Not_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WCA CAPA Not Requested</description>
        <inlineHelpText>WCA CAPA Not Requested</inlineHelpText>
        <label>WCA CAPA Not Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WCA_Compliant__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WCA Compliant</description>
        <inlineHelpText>Audit Group = ANNUAL WCA and
Facility Status = ACTIVE and
Audit Date  &gt;=TODAY()-365</inlineHelpText>
        <label>WCA Compliant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WCA_Due_for_new_listing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WCA Due for new listing</description>
        <inlineHelpText>Audit Group = ANNUAL WCA and
Factory Status  = ACTIVE and
Audit Date = BLANK</inlineHelpText>
        <label>WCA Due for new listing</label>
        <type>Checkbox</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CountryScoreServices.cls
global with sharing class CountryScoreServices {

    
// Calculate WCA Compliant  
 public static CountryScoreCard__c calcWCACompliant(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;

     
   
      integer i = 0;
      
        for(Facility__c fclty : facility) {
            String productGroup = splmap.get(facility[i].Facility_Number__c);        
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
      	   if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp2__c++;
            }
      	   if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp3__c++;
     	    }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp4__c++;
       		 }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp5__c++;
      	  }
          if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp6__c++;
      	  }
          if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp7__c++;
      	  }
          if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp8__c++;
      	    }
 
          if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp9__c++;
      	    }
            
           if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].WCA_Compliant__c == True) {
                  scorecard.PrdGrp10__c++;
      	    }
            i++;
        }
                
        Return scorecard;
        
       }
 
    // Calculate WCA Past Audit Deadline
  public static CountryScoreCard__c calcPastWCAAuditDeadline(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
   
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
     
       
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp9__c++;
        }
         if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].Past_Audit_Deadline_WCA__c == True) {
                  scorecard.PrdGrp10__c++;
        }           
            
            i++;
        }
                
        Return scorecard;
        
       }
    
 // Calculate Due for New Listing / WCA Initial is actually Due for new listing / Name was changed
  public static CountryScoreCard__c calcWCAInitial(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
        
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
     	    if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp2__c++;
            }
      	   if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp3__c++;
      	    }
           if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp4__c++;
            }
           if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp5__c++;
         }
         if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp6__c++;
         }
         if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp7__c++;
         }
         if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp8__c++;
         }
         if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp9__c++;
         }
            
                if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].WCA_Due_for_new_listing__c == True) {
                  scorecard.PrdGrp10__c++;
         }
            i++;
        }
                
        Return scorecard;
        
       }
    
 // Calculate WCA CAPA Not Requested
public static CountryScoreCard__c calcWCACAPANotRequested(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        

        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
     
       
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
             facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
             facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
             facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
             facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp9__c++;
        }
        if(productGroup == scorecard.Product_Group_10__c && 
             facility[i].WCA_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp10__c++;
        }          
            
            i++;
        }
                
        Return scorecard;
        
       }
    
// Calculate Past CAPA Performed
 public static CountryScoreCard__c calcWCACAPAPerformed(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
    
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
     
       
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp8__c++;
        }
            
        if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp9__c++;
        }  
            
         if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].WCA_CAPA_Completed__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard; 
       }
    
// Calculate WCA Past CAPA Deadline
  public static CountryScoreCard__c calcPastWCACAPADeadline(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
         
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp5__c++;
        }
             if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp6__c++;
        }
            if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp7__c++;
        }
            if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp8__c++;
        }
            if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp9__c++;
        }
            if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].Past_CAPA_Deadline_WCA__c == True) {
                  scorecard.PrdGrp10__c++;
        }
            i++;
        }
                
        Return scorecard;
        
       }
    
// Calculate WCA Pending CAPA / pendingWCACAPA
  public static CountryScoreCard__c calcWCAPendingCAPA(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp5__c++;
        }
           if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp6__c++;
        }
           if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp7__c++;
        }
           if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp8__c++;
        }
            
          if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp9__c++;
        }
           if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].Pending_CAPA_WCA__c == True) {
                  scorecard.PrdGrp10__c++;
        }           
            i++;
        }
                
        Return scorecard;
        
       }
   
 // Calculate FS Compliant / compliantFS
public static CountryScoreCard__c calcCompliantFS(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp1__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp9__c++;
        }  
        if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].FS_Compliant__c == True) {
                  scorecard.PrdGrp10__c++;
        }         
            
            i++;
        }
                
        Return scorecard;
        
       }  
    
// Calculate FS Past Audit Deadline / pastFSAuditDeadline
  public static CountryScoreCard__c calcPastFSAuditDeadline(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp9__c++;
        }          
        if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].Past_Audit_Deadline_FS__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard;
        
       } 
// Calculate FS Initial / initialFS
  public static CountryScoreCard__c calcFSInitial(List<Facility__c> facility, Map<String, String> vndmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = vndMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp9__c++;
        }           
         if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].FS_Audit_Required__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard;
        
       } 
 // Calculate FS_CAPA_Not_Required__c
  public static CountryScoreCard__c calcFSCAPANotRequired(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
         
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp9__c++;
        }           
         if(productGroup == scorecard.Product_Group_10__c && 
                facility[i].FS_CAPA_Not_Requested__c == True) {
                  scorecard.PrdGrp10__c++;
        }              
            i++;
        }
                
        Return scorecard;
        
       } 
    
// Calculate FS_CAPA_Performed / performedFSCAPA
  public static CountryScoreCard__c calcFSCAPAPerformed(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
      
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].FS_CAPA_Completed__c == True) {
                  scorecard.PrdGrp9__c++;
        }           
            i++;
        }
                
        Return scorecard;
        
     } 
    
// Calculate FS Past CAPA Deadline / pastFSCAPADeadline
  public static CountryScoreCard__c calcPastFSCAPADeadline(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
         
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp5__c++;
        }
          if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp9__c++;
        }  
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Past_CAPA_Deadline_FS__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            
            
            i++;
        }
                
        Return scorecard;
        
       } 

// Calculate FS Pending CAPA / pendingFSCAPA
  public static CountryScoreCard__c calcPendingFSCAPA(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
       
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp1__c++;
               
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp8__c++;
        }
      if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp9__c++;
        }            
      if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Pending_CAPA_FS__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard;
        
       } 

 
     // Calculate Training Not Required 
  public static CountryScoreCard__c calcTrainNotRequired(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp9__c++;
        }           
       if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Training_not_requested__c == True) {
                  scorecard.PrdGrp10__c++;
        }           
            i++;
        }
                
        Return scorecard;
        
       } 
   // Calculate Training Not Required 
  public static CountryScoreCard__c calcTrainCompleted(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp5__c++;
        }
          if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp9__c++;
        } 
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Training_Completed__c == True) {
                  scorecard.PrdGrp10__c++;
        }             
            
            i++;
        }
                
        Return scorecard;
        
       } 
 // Calculate Training Not Required 
  public static CountryScoreCard__c calcTrainNotCompleted(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup ==  scorecard.Product_Group_6__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp6__c++;
        }
        if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp9__c++;
        }            
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Training_Not_Completed__c == True) {
                  scorecard.PrdGrp10__c++;
        }              
            i++;
        }
                
        Return scorecard;
        
       }
 // Calculate Training Not Required 
  public static CountryScoreCard__c calcEngAuditReq(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp5__c++;
        }
          if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp7__c++;
        }
         if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp8__c++;
        }
         if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp9__c++;
        }            
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Engineering_Audit_Requested__c == 'Yes') {
                  scorecard.PrdGrp10__c++;
        }           
            i++;
        }
                
        Return scorecard;
        
       }
 // Calculate Training Not Required 
  public static CountryScoreCard__c calcEngAuditCompleted(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp4__c++;
        }
            if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp5__c++;
        }
         if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp9__c++;
        }            
       if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Engineering_audit_completed__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard;
        
       }
// Calculate Accord Engineering Audit Not Requested 
  public static CountryScoreCard__c calcEngAuditNotReq(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp9__c++;
        }           
         if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Engineering_Audit_Not_Requested__c == True) {
                  scorecard.PrdGrp10__c++;
        }            
            i++;
        }
                
        Return scorecard;
        
       }
    
 // Calculate Greenlist
  public static CountryScoreCard__c calcGreenlist(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
         
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Green_List_Status__c == 'Unblocked') {
                  scorecard.PrdGrp8__c++;
        }
            i++;
        }
         
        Return scorecard;
        
       }   
 
  // Calculate Greenlist
  public static CountryScoreCard__c calcnonGreenlist(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
         
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp9__c++;
        }
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Green_List_Status__c == 'Blocked') {
                  scorecard.PrdGrp10__c++;
        }
            i++;
        }
         
        Return scorecard;
        
       }   
 
    
 
   // Calculate non Mannual Accepted 
  public static CountryScoreCard__c calcManAcceptedShip(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
        scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Facility_Status__c == 'Manual Accepted Shipments') {
                  scorecard.PrdGrp8__c++;
        }
            i++;
        }
                
        Return scorecard;
        
       }    
 
   // Calculate non Mannual Accepted 
  public static CountryScoreCard__c calcDelisted(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
        
         scorecard.PrdGrp1__c = 0;
        scorecard.PrdGrp2__c = 0;
        scorecard.PrdGrp3__c = 0;
        scorecard.PrdGrp4__c = 0;
        scorecard.PrdGrp5__c = 0;
        scorecard.PrdGrp6__c = 0;
        scorecard.PrdGrp7__c = 0;
        scorecard.PrdGrp8__c = 0;
        scorecard.PrdGrp9__c = 0;
        scorecard.PrdGrp10__c = 0;
        
        integer i = 0; 
        
        for(Facility__c fctry : facility) {
           
            String productGroup = splMap.get(facility[i].Facility_Number__c);
            
            if(productGroup == scorecard.Product_Group_1__c && 
                facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp1__c++;             
            }
         if(productGroup == scorecard.Product_Group_2__c && 
                facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp2__c++;
            }
         if(productGroup == scorecard.Product_Group_3__c && 
                facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp3__c++;
        }
          if(productGroup == scorecard.Product_Group_4__c && 
                facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp4__c++;
        }
        if(productGroup == scorecard.Product_Group_5__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp5__c++;
        }
        if(productGroup == scorecard.Product_Group_6__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp6__c++;
        }
         if(productGroup == scorecard.Product_Group_7__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp7__c++;
        }
        if(productGroup == scorecard.Product_Group_8__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp8__c++;
        }
        if(productGroup == scorecard.Product_Group_9__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp9__c++;
        }
        if(productGroup == scorecard.Product_Group_10__c && 
               facility[i].Facility_Status__c == 'Delisted') {
                  scorecard.PrdGrp10__c++;
        } 
            i++;
        }
                
        Return scorecard;
        
       }   
    
    
     public static CountryScoreCard__c calcAuditScorecards(List<Facility__c> facility, Map<String, String> splmap, CountryScoreCard__c scorecard) {
    

       If(scorecard.Formula__c == '00002') {
       
    	   scorecard = calcPastWCAAuditDeadline(facility, splmap, scorecard);
       }
       
       If(scorecard.Formula__c == '00003') {
    	   scorecard = calcWCAInitial(facility, splmap, scorecard);
       } 
       If(scorecard.Formula__c == '00004') {
    	   scorecard = calcWCACompliant(facility, splmap, scorecard);

       }
       If(scorecard.Formula__c == '00005') {
    	   scorecard = calcWCACAPANotRequested(facility, splmap, scorecard);
       } 
        
       If(scorecard.Formula__c == '00007') {
    	   scorecard = calcWCACAPAPerformed(facility, splmap, scorecard);
       } 
        
       If(scorecard.Formula__c== '00008') {
    	   scorecard = calcPastWCACAPADeadline(facility, splmap, scorecard);
       } 
 
       If(scorecard.Formula__c == '00009') {
    	   scorecard = calcWCAPendingCAPA(facility, splmap, scorecard);
       }

       If(scorecard.Formula__c == '00012') {
    	   scorecard = calcCompliantFS(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00013') {
    	   scorecard = calcPastFSAuditDeadline(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00014') {
    	   scorecard = calcFSInitial(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00015') {
    	   scorecard = calcFSCAPANotRequired(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00016') {
    	   scorecard = calcFSCAPAPerformed(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00017') {
    	   scorecard = calcPastFSCAPADeadline(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00018') {
    	   scorecard = calcPendingFSCAPA(facility, splmap, scorecard);
       }
 

       If(scorecard.Formula__c == '00022') {
    	   scorecard = calcTrainNotRequired(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00023') {
    	   scorecard = calcTrainCompleted(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00025') {
    	   scorecard = calcTrainNotCompleted(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00026') {
    	   scorecard = calcEngAuditNotReq(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00027') {
    	   scorecard = calcEngAuditCompleted(facility, splmap, scorecard);
       }
       If(scorecard.Formula__c == '00028') {
    	   scorecard = calcEngAuditReq(facility, splmap, scorecard);
       }

        If(scorecard.Formula__c == '00030') {
    	   scorecard = calcGreenList(facility, splmap, scorecard);
       }
        If(scorecard.Formula__c == '00031') {
    	   scorecard = calcnonGreenList(facility, splmap, scorecard);
       }
        If(scorecard.Formula__c == '00032') {
    	   scorecard = calcManAcceptedShip(facility, splmap, scorecard);
       }
           If(scorecard.Formula__c == '00033') {
    	   scorecard = calcDelisted(facility, splmap, scorecard);
       }
       Return scorecard;
   }


}