objects/Country__c.object
<CustomObject>
    <description>Country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <description>Production Facility</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FS_Audit_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS Audit Required</description>
        <inlineHelpText>FS Audit Required</inlineHelpText>
        <label>FS Audit Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Due_for_new_listing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>FS Due for new listing</description>
        <inlineHelpText>Audit Group = PERIODIC FS and
Factory Status = ACTIVE and
Audit Date = BLANK and
FS Audit Required = NOT BLANK</inlineHelpText>
        <label>FS Due for new listing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FS_Required_country__c</fullName>
        <description>FS Required country</description>
        <inlineHelpText>FS Required country</inlineHelpText>
        <label>FS Required Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Number__c</fullName>
        <description>Facility Number</description>
        <displayFormat>{0000000}</displayFormat>
        <inlineHelpText>Facility Number</inlineHelpText>
        <label>Facility Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Facility_Status__c</fullName>
        <description>Facility Status</description>
        <inlineHelpText>Facility Status</inlineHelpText>
        <label>Facility Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delisted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Region</description>
        <inlineHelpText>Region</inlineHelpText>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unauthorized_Sub_Contracting__c</fullName>
        <description>Unauthorized Subcontracting</description>
        <inlineHelpText>Unauthorized Subcontracting</inlineHelpText>
        <label>Unauthorized Subcontracting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WCA_Due_for_new_listing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>WCA Due for new listing</description>
        <inlineHelpText>Audit Group = ANNUAL WCA and
Factory Status  = ACTIVE and
Audit Date = BLANK</inlineHelpText>
        <label>WCA Due for new listing</label>
        <type>Checkbox</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Facility_Audits__c.object
<CustomObject>
    <description>Facility Audits</description>
    <fields>
        <fullName>A_Finding__c</fullName>
        <description>A Findings</description>
        <inlineHelpText>A Findings</inlineHelpText>
        <label>A Finding</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Audit_Date__c</fullName>
        <description>Audit Date</description>
        <inlineHelpText>Audit Date</inlineHelpText>
        <label>Audit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Audit_Group__c</fullName>
        <description>Audit Group</description>
        <inlineHelpText>Audit Group</inlineHelpText>
        <label>Audit Group</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual WCA</fullName>
                    <default>true</default>
                    <label>Annual WCA</label>
                </value>
                <value>
                    <fullName>Periodic FS</fullName>
                </value>
                <value>
                    <fullName>WCA Follow Up CAPA</fullName>
                </value>
                <value>
                    <fullName>FS Follow Up CAPA</fullName>
                </value>
                <value>
                    <fullName>On Site Investigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Audit_Request_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Audit Request Date</description>
        <inlineHelpText>Audit Request Date</inlineHelpText>
        <label>Audit Request Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>B1_Findings__c</fullName>
        <description>B1 Findings</description>
        <inlineHelpText>B1 Findings</inlineHelpText>
        <label>B1 Findings</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>B2_6_Findings__c</fullName>
        <description>B2 &lt; 6 Findings</description>
        <inlineHelpText>B2 &lt; 6 Findings</inlineHelpText>
        <label>B2 &lt; 6 Findings</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>B2_Finding__c</fullName>
        <description>B2 Findings</description>
        <inlineHelpText>B2 Findings</inlineHelpText>
        <label>B2 Findings</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>B2_T_Findings__c</fullName>
        <description>B2 + To Findings</description>
        <inlineHelpText>B2 + To Findings</inlineHelpText>
        <label>B2 + T Findings</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAPA_Due_Date__c</fullName>
        <description>CAPA Due Date</description>
        <formula>CASE( 
 Audit_Type__c, 
&quot;WCA CAPA (1 Mnth)&quot;, Audit_Request_Date__c  + 30, 
&quot;WCA CAPA (3 Mnth)&quot;, Audit_Request_Date__c  + 90, 
&quot;WCA CAPA (6 Mnth)&quot;, Audit_Request_Date__c  + 180, 
&quot;Other CAPA (6 Mnth)&quot;, Audit_Request_Date__c  + 180, 
&quot;FS CAPA (1 Mnth)&quot;, Audit_Request_Date__c  + 30, 
&quot;FS CAPA (3 Mnth)&quot;, Audit_Request_Date__c  + 90, 
&quot;FS CAPA (6 Mnth)&quot;, Audit_Request_Date__c  + 180, 
 null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>CAPA Due Date</inlineHelpText>
        <label>CAPA Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility_Number__c</fullName>
        <description>Facility Number</description>
        <formula>Facility__r.Facility_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Facility Number</inlineHelpText>
        <label>Facility Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Facility</description>
        <inlineHelpText>Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Facility Audits</relationshipLabel>
        <relationshipName>Facility_Audits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>Outcome</description>
        <formula>IF( 
OR( 
 ISPICKVAL( Audit_Type__c, &quot;On Site Investigation&quot; ) , 
 ISBLANK(Audit_Date__c)), &quot; &quot;, 

 IF (OR( ISPICKVAL( A_Finding__c , &quot;Yes&quot;), 
 ISPICKVAL( B1_Findings__c , &quot;Yes&quot;)),&quot;High&quot;, 
IF( OR(ISPICKVAL( B2_Finding__c , &quot;Yes&quot;), 
 ISPICKVAL( B2_6_Findings__c , &quot;Yes&quot;), 
 ISPICKVAL(  B2_T_Findings__c  ,&quot;Yes&quot;)),&quot;Medium&quot;,&quot;Low&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Outcome</inlineHelpText>
        <label>Outcome</label>
        <type>Text</type>
    </fields>
    <label>Facility Audits</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Facility Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Audits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Region</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FacilityActionCntrl.cls
global with sharing class FacilityActionCntrl {

        
   webservice static String facilityAction(String facilityId){
       
    
       
        Facility__c facility = [Select i.Name,i.Facility_Number__c,i.Facility_Status__c,i.WCA_Due_for_new_listing__c,
                              i.FS_Due_for_new_listing__c,i.Unauthorized_Sub_Contracting__c,
                              i.FS_Required_country__c,
                              i.FS_Audit_Required__c,i.Country__c,i.Region__c,
                              (Select Name, Audit_Group__c, Audit_Date__c, CAPA_Due_Date__c, Audit_Request_Date__c	,
                               A_Finding__c, B1_Findings__c, B2_T_Findings__c ,B2_6_Findings__c,B2_Finding__c,
                               Outcome__c,Facility_Number__c from Facility_Audits__r ORDER BY Name) 
                              FROM Facility__c i
                              WHERE i.Facility_Number__c = :facilityId LIMIT 1];    
       
            facility = facilityServices.setFSAuditRequired(facility);
       
            facility = facilityServices.rmvdueToWCA(facility);
            facility = facilityServices.rmvdueToWCACAPA(facility);
            facility = facilityServices.rmvdueToFS(facility);
            facility = facilityServices.rmvdueToFSCAPA(facility);
       
            facility = facilityServices.dueforNewLstngFS(facility);
            facility = facilityServices.dueforNewLstngWCA(facility);
       
   //       factory = FactoryServices.setFSCountry(factory);  
       
            facility = facilityServices.compliantWCA(facility);
            facility = facilityServices.compliantFS(facility);
             
            facility = facilityServices.pastWCACAPADeadline(facility);
            facility = facilityServices.pastFSCAPADeadline(facility);
       
            facility = facilityServices.pastWCAAuditDeadline(facility);      
            facility = facilityServices.pastFSAuditDeadline(facility);
       
            facility = facilityServices.findlatestauditdates(facility);
            facility = facilityServices.onsiteinvestigate(facility);       
            facility = facilityServices.calcNoAudits(facility);
       
            facility = facilityServices.pendingWCACAPA(facility);
            facility = facilityServices.pendingFSCAPA(facility);
       
            facility = facilityServices.completedWCACAPA(facility);
            facility = facilityServices.completedFSCAPA(facility);
       
            facility = facilityServices.setOverallRisk(facility);
       
 // Check if the facility has sub contractors
 // Issue a SQL Statement to get the facility with subcontractors
 // Loop through sub facilities and
 // Calculate green status for each facility    
 // save the block status. 
 // If one of the sub contractors has a block status then 
 // set block the main facility.
 // Bypass this logic if the are no sub contractors
 // 
 // 
 // I need a trigger that checks that there are no subcontracting loops
 // master --> sub contractor --> master
 // 
 // 
            facility = facilityServices.calcGreenStatus(facility);
       
           try {
            Database.update(facility);
              }
            catch(DmlException e) {
                return e.getMessage();
          }
       
              Return 'Facility Action Updated';
           }
}