objects/Facility__c.object
<CustomObject>
    <description>Production Facility</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Address Line 1</description>
        <inlineHelpText>Address Line 1</inlineHelpText>
        <label>Address Line 1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>Address Line 2</description>
        <inlineHelpText>Address Line 2</inlineHelpText>
        <label>Address Line 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name_2__c</fullName>
        <description>Facility Name 2</description>
        <inlineHelpText>Facility Name 2</inlineHelpText>
        <label>Facility Name 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Number__c</fullName>
        <description>Facility Number</description>
        <displayFormat>{0000000}</displayFormat>
        <inlineHelpText>Facility Number</inlineHelpText>
        <label>Facility Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Facility_Status__c</fullName>
        <description>Facility Status</description>
        <inlineHelpText>Facility Status</inlineHelpText>
        <label>Facility Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delisted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>Fax</description>
        <inlineHelpText>Fax</inlineHelpText>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Green_List_Status__c</fullName>
        <description>Green List Status</description>
        <inlineHelpText>Green List Status</inlineHelpText>
        <label>Green List Status</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PSTL_Code__c</fullName>
        <description>Postal Code</description>
        <inlineHelpText>Postal Code</inlineHelpText>
        <label>PSTL Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone</description>
        <inlineHelpText>Phone</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Region</description>
        <inlineHelpText>Region</inlineHelpText>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>Region</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <inlineHelpText>Country</inlineHelpText>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Supplier__c.object
<CustomObject>
    <description>Supplier or Vendor</description>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Address Line 1</description>
        <inlineHelpText>Address Line 1</inlineHelpText>
        <label>Address Line 1</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>Address Line 2</description>
        <inlineHelpText>Address Line 2</inlineHelpText>
        <label>Address Line 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <inlineHelpText>City</inlineHelpText>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Supplier</relationshipLabel>
        <relationshipName>Supplier</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <description>Fax</description>
        <inlineHelpText>Fax</inlineHelpText>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Organization</description>
        <inlineHelpText>Organization</inlineHelpText>
        <label>Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit 1</fullName>
                    <default>true</default>
                    <label>Business Unit 1</label>
                </value>
                <value>
                    <fullName>Business Unit 2</fullName>
                </value>
                <value>
                    <fullName>Business Unit 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSTL_Code__c</fullName>
        <description>Postal Code</description>
        <inlineHelpText>Postal Code</inlineHelpText>
        <label>PSTL Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone Number</description>
        <inlineHelpText>Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Country__c</field>
                <operation>equals</operation>
                <valueField>Region__c.Country__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Supplier</relationshipLabel>
        <relationshipName>SupplierRegion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Name_2__c</fullName>
        <description>Supplier Name 2</description>
        <inlineHelpText>Supplier Name 2</inlineHelpText>
        <label>Supplier Name 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Number__c</fullName>
        <description>Supplier Number</description>
        <displayFormat>{0000000}</displayFormat>
        <inlineHelpText>Supplier Number</inlineHelpText>
        <label>Supplier Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Supplier_Status__c</fullName>
        <description>Supplier Status</description>
        <inlineHelpText>Supplier Status</inlineHelpText>
        <label>Supplier Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Delisted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <description>Supplier Type</description>
        <inlineHelpText>Supplier Type</inlineHelpText>
        <label>Supplier Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Offshore</fullName>
                    <default>true</default>
                    <label>Offshore</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Supplier_Facility__c.object
<CustomObject>
    <description>Supplier Facility Relationship</description>
    <fields>
        <fullName>Facility_Number__c</fullName>
        <description>Facility Number</description>
        <formula>Facility__r.Facility_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Facility Number</inlineHelpText>
        <label>Facility Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <description>Facility</description>
        <inlineHelpText>Facility</inlineHelpText>
        <label>Facility</label>
        <referenceTo>Facility__c</referenceTo>
        <relationshipLabel>Suppliers Facilities</relationshipLabel>
        <relationshipName>Suppliers_Facilities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <description>Organization</description>
        <formula>TEXT(Supplier__r.Organization__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Organization</inlineHelpText>
        <label>Organization</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relation_Status__c</fullName>
        <description>Relation Status</description>
        <inlineHelpText>Relation Status</inlineHelpText>
        <label>Relation Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supplier_Name_2__c</fullName>
        <description>Supplier Name</description>
        <formula>Supplier__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Supplier Name</inlineHelpText>
        <label>Supplier Name 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <description>Supplier Name</description>
        <formula>Supplier__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Supplier Name</inlineHelpText>
        <label>Supplier Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Number__c</fullName>
        <description>Supplier Number</description>
        <formula>Supplier__r.Supplier_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Supplier Number</inlineHelpText>
        <label>Supplier Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Status__c</fullName>
        <description>Supplier Status</description>
        <formula>TEXT(Supplier__r.Supplier_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Supplier Status</inlineHelpText>
        <label>Supplier Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Type__c</fullName>
        <description>Supplier Type</description>
        <formula>TEXT(Supplier__r.Supplier_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Supplier Type</inlineHelpText>
        <label>Supplier Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <description>Supplier</description>
        <inlineHelpText>Supplier</inlineHelpText>
        <label>Supplier</label>
        <referenceTo>Supplier__c</referenceTo>
        <relationshipLabel>Suppliers Facilities</relationshipLabel>
        <relationshipName>Suppliers_Facilities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplier Facility</label>
    <nameField>
        <displayFormat>SF-{0000000}</displayFormat>
        <label>Supplier Facility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suppliers Facilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ESIntegrationServices.cls
global class ESIntegrationServices {

//Account Groups 
//This is the only place where it needs to be changed if required
public static String acctgrpSupplier =  'Z012';
public static String acctgrpFacility= 'Z003';  
public static String acctgrpVndFacility= 'Z002'; 
public static String searchTrmVnd = 'BU'; 
public static String searchTrmFct = 'facility';  
public static Integer i = 0;
public static Integer k = 0;
public static String supplno;
public static String rltnStatus;
public static String rltnId;
    

     
//
// Definition of facility response object 
// 
   global class Facility {
          WebService string facilityId;
          WebService String facilityname;
          WebService String facilityname2;
          WebService String address1;
          WebService String address2;
          WebService String city;
          WebService String region;
          WebService String pstl;
          WebService String acctgrp;
          WebService String searchTrm;
          WebService String country;
          WebService String phone;
          WebService String fax;
          WebService String facilitystatus;
          WebService String blockstatus;
          WebService String supplierno;
          WebService String reltnstatus;
          WebService String reltnId;
      
          public Facility(Facility__c facility, String auditcountry, String regionname, String vndno, String rStatus, String reltnId) {
               this.facilityId = facility.facility_Number__c;
               this.facilityname = facility.name;
               this.facilityname2 = facility.facility_Name_2__c;
               this.address1 = facility.Address_Line_1__c;
               this.address2 = facility.Address_Line_2__c;
               this.city = facility.City__c;
               this.region = regionname;
               this.pstl = facility.PSTL_Code__c;
               this.country = auditcountry;
               this.phone = facility.Phone__c;
               this.fax = facility.Fax__c;
               this.acctgrp = acctgrpfacility;
               this.searchTrm = searchTrmFct;
               this.facilitystatus = facility.facility_Status__c;
               this.blockstatus = facility.Green_List_Status__c;
               this.supplierno = vndno;
               this.reltnstatus  = rStatus;
               this.reltnId = reltnId;
            
          }
     }

//
// Definition of facility response object 
// 
   global class Blockstatus {
          WebService string facilityId;
          WebService String facilityname;
          WebService String facilitystatus;
          WebService String blockstatus;

      
          public BlockStatus(facility__c facility) {
               this.facilityId = facility.facility_Number__c;
               this.facilityname = facility.name;
               this.facilitystatus = facility.facility_Status__c;
               this.blockstatus = facility.Green_List_Status__c;
            
          }
     }
       
    
//
// Definition of facility response object 
// 
   global class SupplierFacility{
          WebService String supplierno;
          WebService string factno;
          WebService String status;
          WebService String suppliername;
          WebService String facilityname;
          WebService String fctaddress1;
          WebService String fctaddress2;
          WebService String fctcity;
          Webservice String acctgrp;
  //      Webservice String searchterm;
          WebService String fctregion;
          WebService String fctpstl;
          WebService String fctcountry;
          WebService String fctphone;
          WebService String fctfax;
          WebService String type;
          WebService String reltnid;

 
          public Supplierfacility(Supplier_facility__c vndfacility, facility__c facility,String country, String region) {
               this.supplierno = vndfacility.Supplier_Number__c;
               this.factno = vndfacility.facility_Number__c;
               this.status = vndfacility.Relation_Status__c;
               this.reltnid = vndfacility.Name;
               this.suppliername = vndfacility.Supplier_Name__c;
               this.type = vndfacility.Supplier_Type__c;
               this.facilityname = facility.Name;
               this.fctaddress1 = facility.Address_Line_1__c;
               this.fctaddress2 = facility.Address_Line_2__c;
               this.fctcity = facility.City__c;
               this.fctregion = region;
               this.fctpstl = facility.PSTL_Code__c;
               this.fctcountry = country;
               this.acctgrp = acctgrpVndfacility;
               this.fctphone = facility.Phone__c;
               this.fctfax = facility.Fax__c;
          
          }
     }
//
// Definition of Supplier response object 
// 
    
    global class Supplier {
          WebService String supplierId;
          WebService String suppliername;
          WebService String suppliername2;
 //         WebService String address1;
 //         WebService String address2;
 //         WebService String city;
 //         WebService String region;
 //         WebService String pstl;
          WebService String acctgrp;
          WebService String searchTrm;
          WebService String country;
  //        WebService String phone;
 //         WebService String fax;
          WebService String suppliertype;
          WebService String supplierstatus;
 
        
          public Supplier() {}
 
          public Supplier(Supplier__c supplier, String auditcountry) {
               this.supplierId = supplier.Supplier_Number__c;
               this.suppliername = supplier.Name;
               this.suppliername2 = supplier.Supplier_Name_2__c;
               this.country = auditcountry;
               this.acctgrp = acctgrpSupplier;
               this.searchTrm = searchTrmVnd;
               this.suppliertype = supplier.Supplier_Type__c;
               this.supplierstatus = supplier.Supplier_Status__c;
            

          }
     }

 //
 // Web service to retrieve the FacilityBlock Status over a given time period
 // Input is either D,H,M for timeUnit and integer for timeValue
 // Example:
 // D,1 = Give me all changes from the last day
 // H,3 = Give me all changes from the last 3 hours
 // M,40 = Give me all changes from the last 40 minutes

 
    
 webService static List<Blockstatus> getBlockstatus(String timeUnit, integer timeValue){
        
    List<BlockStatus> blockstatus = new List<Blockstatus>();
        
        Datetime mydatetime;
        mydatetime = Datetime.now();
        
        if(timeUnit == 'D'){
            timeValue = timeValue * -1;
            mydatetime = mydatetime.addDays(timeValue);  
        } else {
            if(timeUnit == 'H'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addHours(timeValue);
                
            } else {
               if(timeUnit == 'M'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addMinutes(timeValue);  
            }
            }
        }
         
        String returndate = mydatetime.format();
        
        List<facility__c> nfacility = [Select i.Name, i.facility_Name_2__c, i.facility_Number__c, i.facility_Status__c,
                                    i.Address_Line_1__c, i.Address_Line_2__c,i.city__c,i.region__c,i.PSTL_Code__c,
                                    i.Country__c,i.phone__C,i.fax__c,i.Green_List_Status__c,
                             (Select facility_Number__c, 
                              Supplier_Number__c,Relation_Status__c, Organization__c, Name, Contract_Signed_Date__c  from Suppliers_Facilities__r order by Name) 
                                FROM Facility__c i                                         
                                  WHERE i.LastModifiedDate > :mydatetime];

  // Split up the vendorfacility relationship record  from facility
 //     
        
       List<Supplier_facility__c> vndfacility = new List<Supplier_facility__c>();
       List<Supplier_facility__c> nvndfacility = new List<Supplier_facility__c>();
       i = 0;
       k = 0;
              
        for(facility__c fctry : nfacility){
           vndfacility = nfacility[i].Suppliers_Facilities__r;
           
            k = 0;
            for(Supplier_facility__c vndfctry : vndfacility){
                nvndfacility.add(vndfacility[k]);
                k++;               
            }
         i++;
        }      
 
        i = 0;
        k = 0;
        boolean fndsts = false;
 
     
  // The purpose of this loop is to further check if the relationship records have some condition for which
  // the facility should be transferred. 
  //    
     
        for(facility__c fctry : nfacility)   {
             k = 0;
               for(Supplier_facility__c vndfctry : nvndfacility ){
 
                   blockstatus.add(new Blockstatus(fctry)); 
                   k++;
               }
            i++;        
        }
     return blockstatus;
    } 
     
 //
 // Web service to retrieve all changed factories over a given time period
 // Input is either D,H,M for timeUnit and integer for timeValue
 // Example:
 // D,1 = Give me all changes from the last day
 // H,3 = Give me all changes from the last 3 hours
 // M,40 = Give me all changes from the last 40 minutes

    
    webService static List<facility> getFacilities(String timeUnit, integer timeValue){
       
        List<facility> facility = new List<facility>();
        
        Datetime mydatetime;
        mydatetime = Datetime.now();
        
        if(timeUnit == 'D'){
            timeValue = timeValue * -1;
            mydatetime = mydatetime.addDays(timeValue);  
        } else {
            if(timeUnit == 'H'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addHours(timeValue);
                
            } else {
               if(timeUnit == 'M'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addMinutes(timeValue);  
            }
            }
        }
         
        String returndate = mydatetime.format();
        
        List<facility__c> nfacility = [Select i.Name, i.facility_Name_2__c, i.facility_Number__c, i.facility_Status__c,
                                    i.Address_Line_1__c, i.Address_Line_2__c,i.city__c,i.region__c,i.PSTL_Code__c,
                                    i.Country__c,i.phone__C,i.fax__c,i.Green_List_Status__c,i.LastModifiedDate,
                             (Select facility_Number__c,Supplier_Number__c,Relation_Status__c, Organization__c, Name, Contract_Signed_Date__c  from Suppliers_Facilities__r order by Name) 
                                FROM facility__c i                                         
                                  WHERE i.LastModifiedDate > :mydatetime];

        
 // Split up the vendorfacility relationship record  from facility
 //     
        
       List<Supplier_facility__c> vndfacility = new List<Supplier_facility__c>();
       List<Supplier_facility__c> nvndfacility = new List<Supplier_facility__c>();
       i = 0;
       k = 0;
              
        for(facility__c fctry : nfacility){
           vndfacility = nfacility[i].Suppliers_Facilities__r;
            k = 0;
            for(Supplier_facility__c vndfctry : vndfacility){
                nvndfacility.add(vndfacility[k]);
                k++;               
            }
         i++;
        }     
           
     
        i = 0;
        k = 0;
        boolean fndsts = false;
 
              
        List<Country__c> countryList = [Select i.id, i.Name From Country__c i];
        List<Region__c> regionList = [Select i.id, i.Name From Region__c i];
                                               
        Map<String, String> cntryMap = new Map<String, String>();
        Map<String, String> regionMap = new Map<String, String>();

        
// Load Countries into a map
       i = 0;
       for (Country__c cntry : countryList){ 
          cntryMap.put(countryList[i].id, countryList[i].Name);    
          i++;
          }   
        
 // Load Regions into a map       
        i = 0;
       for (Region__c regn : regionList){ 
          regionMap.put(regionList[i].id, regionList[i].Name);    
          i++;
        }
        
       i = 0; 
       for(facility__c fctry : nfacility)   {
           
                String countryname = cntryMap.get(nfacility[i].Country__c);
                String regionname = regionMap.get(nfacility[i].Region__c);
     
            k = 0;
            for(Supplier_facility__c vndfctry : nvndfacility ){
           
    
                fndsts = true;
                supplno = nvndfacility[k].Supplier_Number__c;
                rltnStatus = nvndfacility[k].Relation_Status__c; 
                rltnId = nvndfacility[k].Name;
                facility.add(new facility(nfacility[i],countryname,regionname,supplno,rltnStatus,rltnId));  
                    
                k++;
               }

     //       if(!fndsts){
     //             vendorno =  '  ';
     //             rltnStatus =  ' '; 
     //             rltnId =  ' '; 
     //             facility.add(new facility(nfacility[i],vendorno,rltnStatus,rltnId));  
             
     //       } 
            fndsts = false;
            i++;
        }     
              
        Return facility;               
    }
 
    

 //
 // Web service to retrieve all changed vendors over a given time period
 // Input it is either D,H,M for timeUnit and integer for timeValue
 // Example:
 // D,1 = Give me all changes from the last day
 // H,3 = Give me all changes from the last 3 hours
 // M,40 = Give me all changes from the last 40 minutes
    
  webService static List<Supplier> getSuppliers(String timeUnit, integer timeValue){
       
        List<Supplier> result = new List<Supplier>();
        
        Datetime mydatetime;
        mydatetime = Datetime.now();
        
        if(timeUnit == 'D'){
            timeValue = timeValue * -1;
            mydatetime = mydatetime.addDays(timeValue);  
        } else {
            if(timeUnit == 'H'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addHours(timeValue);
                
            } else {
               if(timeUnit == 'M'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addMinutes(timeValue);  
            }
            }
        }
         
        String returndate = mydatetime.format();
        String auditcountry;
      
        i = 0;
        List<Supplier__c> nvendor = [select Supplier_Number__c,
            Name, Supplier_Name_2__c, Address_Line_1__c, Address_Line_2__c, City__c,  Region__c,
            Country__c, PSTL_code__c, Phone__c, FAX__c, Supplier_Status__c, Supplier_Type__c, Organization__c,
            Contract_Signed_Date__c
            From Supplier__c i
            WHERE i.LastModifiedDate > :mydatetime AND i.Contract_Signed_Date__c != Null];
       
     
        i = 0;
        k = 0;
        boolean fndsts = false;
           
        List<Country__c> countryList = [Select i.id, i.Name From Country__c i];
                                                   
        Map<String, String> cntryMap = new Map<String, String>();
  

        
// Load Countries into a map
       i = 0;
       for (Country__c cntry : countryList){ 
          cntryMap.put(countryList[i].id, countryList[i].Name);    
          i++;
          }   
        
      i = 0;
      
        for(Supplier__c vendor: nvendor) 
        {
            
         if(nvendor[i].Country__c != null) {
            String countryname = cntryMap.get(nvendor[i].Country__c);   
            auditcountry = countryname;
         }else {
            auditcountry = '';
         }
        
         result.add(new Supplier(vendor,auditcountry));
         i++;
        }      
        Return result;
        
        
    }

 //
 // Web service to retrieve all changed vendor/facility relationship over a given time period
 // Input it is either D,H,M for timeUnit and integer for timeValue
 // Example:
 // D,1 = Give me all changes from the last day
 // H,3 = Give me all changes from the last 3 hours
 // M,40 = Give me all changes from the last 40 minutes

    
    webService static List<Supplierfacility> getSupplierfacility(String timeUnit, integer timeValue){
       
        List<Supplierfacility> result = new List<Supplierfacility>();
        
        Datetime mydatetime;
        mydatetime = Datetime.now();
        
        if(timeUnit == 'D'){
            timeValue = timeValue * -1;
            mydatetime = mydatetime.addDays(timeValue);  
        } else {
            if(timeUnit == 'H'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addHours(timeValue);
                
            } else {
               if(timeUnit == 'M'){
                 timeValue = timeValue * -1;
                 mydatetime = mydatetime.addMinutes(timeValue);  
            }
            }
        }
         
        String returndate = mydatetime.format();
             
        List<Country__c> countryList = [Select i.id, i.Name From Country__c i];
        List<Region__c> regionList = [Select i.id, i.Name From Region__c i];
                                               
        Map<String, String> cntryMap = new Map<String, String>();
        Map<String, String> regionMap = new Map<String, String>();

        
// Load Countries into a map
       i = 0;
       for (Country__c cntry : countryList){ 
          cntryMap.put(countryList[i].id, countryList[i].Name);    
          i++;
          }   
        
 // Load Regions into a map       
        i = 0;
       for (Region__c regn : regionList){ 
          regionMap.put(regionList[i].id, regionList[i].Name);    
          i++;
        }
             
        
        for(Supplier_Facility__c vndfacility: [
            select i.facility_Number__c,
                   i.Supplier_Number__c,
                   i.Supplier_Type__c,
                   i.Relation_Status__c,
                   i.Name,
                   i.Supplier_Name__c
 
            From Supplier_facility__c i
            WHERE i.LastModifiedDate > :mydatetime AND i.Contract_Signed_Date__c != Null])  
        {
           String auditcountry;
           String regionname;
            
             facility__c facility = [Select i.Name,i.facility_Name_2__c, i.Address_Line_1__c, i.Address_Line_2__c, 
                 i.City__c, i.Region__c, i.Country__c, i.PSTL_Code__c, i.Phone__c, i.Fax__c 
                 from facility__c i
                 where i.facility_Number__c = :vndfacility.facility_Number__c Limit 1];
            
// Get the country
// 
          if(facility.Country__c != null) {
                String countryname = cntryMap.get(facility.Country__c);           
            auditcountry = countryname;
              }else {
            auditcountry = '';
          }
 
// Get the Region 
         if(facility.Region__c != null) {
              String region = regionMap.get(facility.Region__c);      
            regionname = region;
              }else {
            regionname = '';
          }         
            
                
            
            result.add(new Supplierfacility(vndfacility,facility,auditcountry,regionname));
        }     
            
        Return result;      
        
    }  
    

}